version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
     POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      - DATABASE_URI=postgresql+psycopg2://postgres:admin@db/postgres
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin
    stdin_open: true
